#!/bin/bash
# Bash script to quickly version bump all Islandora Foundation modules for a release.

# Usage info
show_help() {
  cat << EOF
  Usage: ${0##*/} [-h] [-m MODULE LIST] [-c COMMIT MESSAGE] ...
  Version bump all Islandora Foundation modules.
    
      -h                  display this help and exit
      -m MODULE LIST      path to line delimited list of modules.
      -c COMMIT MESSAGE   commit message. example: "Version bump for 7.x-1.4"
EOF
}                

ISLANDORA_COMMIT=""
ISLANDORA_MODULES_LIST=""

OPTIND=1

while getopts "h:m:c:" opt; do
  case "$opt" in
    h)
      show_help
      exit 0
      ;;
    m) ISLANDORA_MODULES_LIST=$OPTARG
      ;;
    c) ISLANDORA_COMMIT=$OPTARG
      ;;      
    '?')
      show_help >&2
      exit 1
      ;;
  esac
done

if [[ -n $opt ]]; then
  # version bump modules
  cat "$ISLANDORA_MODULES_LIST" | while read line; do
    cd "$line"
    grep -rl "version = 7.x-dev" | xargs sed -i 's#version = 7.x-dev#version = 7.x-1.6-RC1#g'
    git commit -m "$ISLANDORA_COMMIT" .
    git push origin 7.x-1.6
    cd ..
  done
fi
